#BaseURL = "http://coderzh.github.io/hugo-pacman-theme/"
BaseURL = "/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "younglinuxer"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true

###添加评论
DuoShuoShortName = 'younglinuxer'
DisqusShortName = "https://https-younglinuxer-github-io-hugo"

[Author]
  Name = "younglinxer"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  AuthorHomepage = "http://blog.youngblog.cc"
  BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = ""
  Subtitle = "沉迷技术的大部分人,看上去都是猥琐的,内心却是善良的"
  Weibo = "coderzh"
  WeiboID = 1816308191
  Twitter = "coderzh"
  GitHub = "coderzh"
  Facebook = "coderzh"
  LinkIn = "coderzh"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2018年06月05日"
  MonthFormat = "2018年06月"
  FancyBox = true

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Disqus]
    ShortName = "coderzh"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
#    Archive = "归档"
    Archive = "歌单"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "推荐书籍"
    URL = "/book"
    Weight = 2
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 3
